import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react"
import type { ReactNode } from "react"
import { staticTranslations } from "@/context/staticTranslations"

export type Language = "zh-CN" | "zh-TW" | "en"

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, fallback?: string) => string
  st: (text: string) => string
}

const LANGUAGE_STORAGE_KEY = "kawang_language"

const translations: Record<Language, Record<string, string>> = {
  "zh-CN": {
    brand: "小野卡铺",
    "nav.home": "首页",
    "nav.announcements": "公告",
    "nav.about": "关于",
    "nav.orders": "订单",
    "nav.orderQuery": "游客查询",
    "nav.login": "登录",
    "nav.profile": "个人中心",
    "nav.logout": "退出登录",
    "nav.translate": "翻译",
    "nav.theme": "主题",
    "nav.light": "亮色",
    "nav.dark": "暗色",
    "language.simplified": "简体",
    "language.traditional": "繁体",
    "language.english": "英语",
    "common.loading": "加载中...",
    "common.copy": "复制",
    "common.copied": "已复制",
    "common.cancel": "取消",
    "common.processing": "处理中...",
    "common.autoDelivery": "自动发卡",
    "common.outOfStock": "售罄",
    "common.buy": "购买",
    "common.buyNow": "立即购买",
    "common.stock": "库存",
    "common.supportOnline": "售后在线",
    "common.reliable": "稳定靠谱",
    "common.noLoginPurchase": "免登录购买",
    "home.stockEnough": "库存充足",
    "home.emptyProductsTitle": "暂无商品",
    "home.emptyProductsDesc": "当前分类暂未上架商品，切换其他分类看看。",
    "home.chooseCategory": "选择分类",
    "home.allProducts": "全部商品",
    "home.showAllCategories": "显示所有分类",
    "home.all": "全部",
    "home.allSubtitle": "所有商品",
    "home.category.vip": "会员",
    "home.category.game": "游戏",
    "home.category.app": "软件",
    "home.category.more": "更多",
    "product.cardFallback": "卡",
    "product.defaultDescription": "售后在线",
    "auth.login.title": "登录账号",
    "auth.login.subtitle": "输入账号和密码，系统会自动识别身份。",
    "auth.account": "账号",
    "auth.accountPlaceholder": "用户名 / 邮箱",
    "auth.password": "密码",
    "auth.passwordPlaceholder": "请输入登录密码",
    "auth.remember": "记住登录状态",
    "auth.forgotPassword": "忘记密码",
    "auth.login": "登录",
    "auth.loggingIn": "登录中...",
    "auth.noAccountRegister": "没有账号？立即注册",
    "auth.loginBadge": "个人小店",
    "auth.loginHeroTitle": "个人卡网 · 自动发卡",
    "auth.loginHeroDesc": "精选虚拟商品，付款后自动交付卡密。",
    "auth.browseProducts": "浏览商品",
    "auth.queryOrders": "查询订单",
    "auth.featureAutoTitle": "24 小时自动发卡",
    "auth.featureAutoDesc": "付款后无需等待人工处理",
    "auth.featureQueryTitle": "订单随时查询",
    "auth.featureQueryDesc": "手机号或订单号找回卡密",
    "auth.featureSupportTitle": "小店售后在线",
    "auth.featureSupportDesc": "异常订单可联系店主处理",
    "auth.purchaseFlow": "购买流程",
    "auth.flowChoose": "1. 选择商品",
    "auth.flowPay": "2. 完成付款",
    "auth.flowDelivery": "3. 自动取卡密",
    "auth.flowQuery": "4. 订单可查询",
    "auth.register.title": "注册账号",
    "auth.registerBadge": "买家账号",
    "auth.registerHeroTitle": "注册后保存订单记录",
    "auth.registerHeroDesc": "登录账号后可查看购买记录、复制卡密和追踪订单状态。",
    "auth.registerSubtitle": "注册账号后可保存购买记录，随时查询订单状态。",
    "auth.username": "用户名",
    "auth.usernamePlaceholder": "例如：xiaoye2026",
    "auth.email": "邮箱",
    "auth.emailPlaceholder": "输入邮箱",
    "auth.emailPlaceholderLong": "输入你的邮箱",
    "auth.emailResetPlaceholder": "请输入注册邮箱",
    "auth.code": "验证码",
    "auth.codePlaceholder": "输入短信验证码",
    "auth.sendCode": "获取验证码",
    "auth.sending": "发送中",
    "auth.setPassword": "设置密码",
    "auth.newPassword": "新密码",
    "auth.confirmPassword": "确认密码",
    "auth.passwordMinPlaceholder": "至少 8 位",
    "auth.passwordStrongPlaceholder": "至少 8 位，建议包含数字和字母",
    "auth.confirmPasswordPlaceholder": "再次输入新密码",
    "auth.agreeTerms": "同意服务条款与隐私政策",
    "auth.agreeTermsLong": "我已阅读并同意服务条款与隐私政策",
    "auth.register": "注册",
    "auth.registering": "注册中...",
    "auth.hasAccountLogin": "已有账号？去登录",
    "auth.reset.title": "重置密码",
    "auth.resetBadge": "账号恢复",
    "auth.resetHeroTitle": "找回账号，继续查询订单",
    "auth.resetHeroDesc": "通过邮箱验证码验证身份，恢复登录后继续管理你的卡密。",
    "auth.resetSubtitle": "通过邮箱验证码验证身份，重新设置登录密码。",
    "auth.phone": "手机号",
    "auth.phonePlaceholder": "请输入注册手机号",
    "auth.resetPassword": "重置密码",
    "auth.resetting": "重置中...",
    "auth.backToLogin": "想起密码？返回登录",
    "auth.needEmail": "请先输入邮箱",
    "auth.codeSent": "验证码已发送",
    "auth.sendCodeFailed": "发送验证码失败",
    "auth.registerSuccess": "注册成功",
    "auth.registerFailed": "注册失败",
    "auth.resetSuccess": "密码已重置",
    "auth.resetFailed": "重置密码失败",
    "auth.loginFailed": "登录失败，请检查账号密码",
    "auth.retryLater": "请在{minutes}分钟后重试",
    "profile.title": "个人中心",
    "profile.subtitle": "查看当前登录账号的信息。",
    "profile.accountInfo": "账号信息",
    "profile.username": "用户名",
    "profile.email": "邮箱",
    "profile.phone": "手机号",
    "profile.role": "角色",
    "profile.userId": "用户 ID",
    "profile.status": "账号状态",
    "profile.statusActive": "正常",
    "profile.statusDisabled": "已禁用",
    "profile.createdAt": "创建时间",
    "profile.updatedAt": "更新时间",
    "profile.roleAdmin": "管理员",
    "profile.roleBuyer": "普通用户",
    "profile.navProfile": "个人资料",
    "profile.navOrders": "我的订单",
    "profile.navSecurity": "账号安全",
    "profile.quickActions": "快捷操作",
    "profile.viewOrders": "查看订单",
    "profile.goAdmin": "进入后台",
    "profile.accountSecurity": "账号安全",
    "profile.accountSecurityDesc": "用于管理登录密码、邮箱验证与账号状态。",
  },
  "zh-TW": {
    brand: "小野卡鋪",
    "nav.home": "首頁",
    "nav.announcements": "公告",
    "nav.about": "關於",
    "nav.orders": "訂單",
    "nav.orderQuery": "遊客查詢",
    "nav.login": "登入",
    "nav.profile": "個人中心",
    "nav.logout": "退出登入",
    "nav.translate": "翻譯",
    "nav.theme": "主題",
    "nav.light": "亮色",
    "nav.dark": "暗色",
    "language.simplified": "簡體",
    "language.traditional": "繁體",
    "language.english": "英語",
    "common.loading": "載入中...",
    "common.copy": "複製",
    "common.copied": "已複製",
    "common.cancel": "取消",
    "common.processing": "處理中...",
    "common.autoDelivery": "自動發卡",
    "common.outOfStock": "售罄",
    "common.buy": "購買",
    "common.buyNow": "立即購買",
    "common.stock": "庫存",
    "common.supportOnline": "售後在線",
    "common.reliable": "穩定可靠",
    "common.noLoginPurchase": "免登入購買",
    "home.stockEnough": "庫存充足",
    "home.emptyProductsTitle": "暫無商品",
    "home.emptyProductsDesc": "目前分類暫未上架商品，切換其他分類看看。",
    "home.chooseCategory": "選擇分類",
    "home.allProducts": "全部商品",
    "home.showAllCategories": "顯示所有分類",
    "home.all": "全部",
    "home.allSubtitle": "所有商品",
    "home.category.vip": "會員",
    "home.category.game": "遊戲",
    "home.category.app": "軟體",
    "home.category.more": "更多",
    "product.cardFallback": "卡",
    "product.defaultDescription": "售後在線",
    "auth.login.title": "登入帳號",
    "auth.login.subtitle": "輸入帳號和密碼，系統會自動識別身份。",
    "auth.account": "帳號",
    "auth.accountPlaceholder": "用戶名 / 郵箱",
    "auth.password": "密碼",
    "auth.passwordPlaceholder": "請輸入登入密碼",
    "auth.remember": "記住登入狀態",
    "auth.forgotPassword": "忘記密碼",
    "auth.login": "登入",
    "auth.loggingIn": "登入中...",
    "auth.noAccountRegister": "沒有帳號？立即註冊",
    "auth.loginBadge": "個人小店",
    "auth.loginHeroTitle": "個人卡網 · 自動發卡",
    "auth.loginHeroDesc": "精選虛擬商品，付款後自動交付卡密。",
    "auth.browseProducts": "瀏覽商品",
    "auth.queryOrders": "查詢訂單",
    "auth.featureAutoTitle": "24 小時自動發卡",
    "auth.featureAutoDesc": "付款後無需等待人工處理",
    "auth.featureQueryTitle": "訂單隨時查詢",
    "auth.featureQueryDesc": "手機號或訂單號找回卡密",
    "auth.featureSupportTitle": "小店售後在線",
    "auth.featureSupportDesc": "異常訂單可聯繫店主處理",
    "auth.purchaseFlow": "購買流程",
    "auth.flowChoose": "1. 選擇商品",
    "auth.flowPay": "2. 完成付款",
    "auth.flowDelivery": "3. 自動取卡密",
    "auth.flowQuery": "4. 訂單可查詢",
    "auth.register.title": "註冊帳號",
    "auth.registerBadge": "買家帳號",
    "auth.registerHeroTitle": "註冊後保存訂單記錄",
    "auth.registerHeroDesc": "登入帳號後可查看購買記錄、複製卡密和追蹤訂單狀態。",
    "auth.registerSubtitle": "註冊帳號後可保存購買記錄，隨時查詢訂單狀態。",
    "auth.username": "用戶名",
    "auth.usernamePlaceholder": "例如：xiaoye2026",
    "auth.email": "郵箱",
    "auth.emailPlaceholder": "輸入郵箱",
    "auth.emailPlaceholderLong": "輸入你的郵箱",
    "auth.emailResetPlaceholder": "請輸入註冊郵箱",
    "auth.code": "驗證碼",
    "auth.codePlaceholder": "輸入簡訊驗證碼",
    "auth.sendCode": "獲取驗證碼",
    "auth.sending": "發送中",
    "auth.setPassword": "設定密碼",
    "auth.newPassword": "新密碼",
    "auth.confirmPassword": "確認密碼",
    "auth.passwordMinPlaceholder": "至少 8 位",
    "auth.passwordStrongPlaceholder": "至少 8 位，建議包含數字和字母",
    "auth.confirmPasswordPlaceholder": "再次輸入新密碼",
    "auth.agreeTerms": "同意服務條款與隱私政策",
    "auth.agreeTermsLong": "我已閱讀並同意服務條款與隱私政策",
    "auth.register": "註冊",
    "auth.registering": "註冊中...",
    "auth.hasAccountLogin": "已有帳號？去登入",
    "auth.reset.title": "重設密碼",
    "auth.resetBadge": "帳號恢復",
    "auth.resetHeroTitle": "找回帳號，繼續查詢訂單",
    "auth.resetHeroDesc": "透過郵箱驗證碼驗證身份，恢復登入後繼續管理你的卡密。",
    "auth.resetSubtitle": "透過郵箱驗證碼驗證身份，重新設定登入密碼。",
    "auth.phone": "手機號",
    "auth.phonePlaceholder": "請輸入註冊手機號",
    "auth.resetPassword": "重設密碼",
    "auth.resetting": "重設中...",
    "auth.backToLogin": "想起密碼？返回登入",
    "auth.needEmail": "請先輸入郵箱",
    "auth.codeSent": "驗證碼已發送",
    "auth.sendCodeFailed": "發送驗證碼失敗",
    "auth.registerSuccess": "註冊成功",
    "auth.registerFailed": "註冊失敗",
    "auth.resetSuccess": "密碼已重設",
    "auth.resetFailed": "重設密碼失敗",
    "auth.loginFailed": "登入失敗，請檢查帳號密碼",
    "auth.retryLater": "請在{minutes}分鐘後重試",
    "profile.title": "個人中心",
    "profile.subtitle": "查看目前登入帳號的資訊。",
    "profile.accountInfo": "帳號資訊",
    "profile.username": "用戶名",
    "profile.email": "郵箱",
    "profile.phone": "手機號",
    "profile.role": "角色",
    "profile.userId": "用戶 ID",
    "profile.status": "帳號狀態",
    "profile.statusActive": "正常",
    "profile.statusDisabled": "已停用",
    "profile.createdAt": "建立時間",
    "profile.updatedAt": "更新時間",
    "profile.roleAdmin": "管理員",
    "profile.roleBuyer": "普通用戶",
    "profile.navProfile": "個人資料",
    "profile.navOrders": "我的訂單",
    "profile.navSecurity": "帳號安全",
    "profile.quickActions": "快捷操作",
    "profile.viewOrders": "查看訂單",
    "profile.goAdmin": "進入後台",
    "profile.accountSecurity": "帳號安全",
    "profile.accountSecurityDesc": "用於管理登入密碼、郵箱驗證與帳號狀態。",
  },
  en: {
    brand: "Kawang Shop",
    "nav.home": "Home",
    "nav.announcements": "News",
    "nav.about": "About",
    "nav.orders": "Orders",
    "nav.orderQuery": "Guest Lookup",
    "nav.login": "Login",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.translate": "Language",
    "nav.theme": "Theme",
    "nav.light": "Light",
    "nav.dark": "Dark",
    "language.simplified": "Simplified",
    "language.traditional": "Traditional",
    "language.english": "English",
    "common.loading": "Loading...",
    "common.copy": "Copy",
    "common.copied": "Copied",
    "common.cancel": "Cancel",
    "common.processing": "Processing...",
    "common.autoDelivery": "Auto delivery",
    "common.outOfStock": "Sold out",
    "common.buy": "Buy",
    "common.buyNow": "Buy now",
    "common.stock": "Stock",
    "common.supportOnline": "Support online",
    "common.reliable": "Reliable",
    "common.noLoginPurchase": "Guest checkout",
    "home.stockEnough": "In stock",
    "home.emptyProductsTitle": "No products",
    "home.emptyProductsDesc": "No products are listed in this category yet. Try another category.",
    "home.chooseCategory": "Choose Category",
    "home.allProducts": "All Products",
    "home.showAllCategories": "Show all categories",
    "home.all": "All",
    "home.allSubtitle": "All products",
    "home.category.vip": "Member",
    "home.category.game": "Game",
    "home.category.app": "Software",
    "home.category.more": "More",
    "product.cardFallback": "Card",
    "product.defaultDescription": "Support online",
    "auth.login.title": "Login",
    "auth.login.subtitle": "Enter your account and password. Your role will be detected automatically.",
    "auth.account": "Account",
    "auth.accountPlaceholder": "Username / Email",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter password",
    "auth.remember": "Remember me",
    "auth.forgotPassword": "Forgot password",
    "auth.login": "Login",
    "auth.loggingIn": "Logging in...",
    "auth.noAccountRegister": "No account? Register",
    "auth.loginBadge": "Personal Shop",
    "auth.loginHeroTitle": "Personal Card Shop",
    "auth.loginHeroDesc": "Selected virtual products with automatic delivery after payment.",
    "auth.browseProducts": "Browse products",
    "auth.queryOrders": "Query orders",
    "auth.featureAutoTitle": "24/7 auto delivery",
    "auth.featureAutoDesc": "No manual processing after payment",
    "auth.featureQueryTitle": "Order lookup anytime",
    "auth.featureQueryDesc": "Recover codes by phone or order number",
    "auth.featureSupportTitle": "Shop support online",
    "auth.featureSupportDesc": "Contact support for abnormal orders",
    "auth.purchaseFlow": "Purchase Flow",
    "auth.flowChoose": "1. Choose product",
    "auth.flowPay": "2. Complete payment",
    "auth.flowDelivery": "3. Receive code",
    "auth.flowQuery": "4. Query order",
    "auth.register.title": "Register",
    "auth.registerBadge": "Buyer Account",
    "auth.registerHeroTitle": "Save Orders After Signup",
    "auth.registerHeroDesc": "View purchase records, copy codes, and track order status after login.",
    "auth.registerSubtitle": "Create an account to save purchase records and query orders anytime.",
    "auth.username": "Username",
    "auth.usernamePlaceholder": "e.g. xiaoye2026",
    "auth.email": "Email",
    "auth.emailPlaceholder": "Enter email",
    "auth.emailPlaceholderLong": "Enter your email",
    "auth.emailResetPlaceholder": "Enter registered email",
    "auth.code": "Code",
    "auth.codePlaceholder": "Enter verification code",
    "auth.sendCode": "Send code",
    "auth.sending": "Sending",
    "auth.setPassword": "Set password",
    "auth.newPassword": "New password",
    "auth.confirmPassword": "Confirm password",
    "auth.passwordMinPlaceholder": "At least 8 characters",
    "auth.passwordStrongPlaceholder": "At least 8 characters, numbers and letters recommended",
    "auth.confirmPasswordPlaceholder": "Enter new password again",
    "auth.agreeTerms": "Agree to Terms and Privacy Policy",
    "auth.agreeTermsLong": "I agree to the Terms and Privacy Policy",
    "auth.register": "Register",
    "auth.registering": "Registering...",
    "auth.hasAccountLogin": "Have an account? Login",
    "auth.reset.title": "Reset Password",
    "auth.resetBadge": "Account Recovery",
    "auth.resetHeroTitle": "Recover Account, Keep Managing Orders",
    "auth.resetHeroDesc": "Verify your identity by email code and continue managing your card codes.",
    "auth.resetSubtitle": "Verify by email code and set a new login password.",
    "auth.phone": "Phone",
    "auth.phonePlaceholder": "Enter registered phone",
    "auth.resetPassword": "Reset password",
    "auth.resetting": "Resetting...",
    "auth.backToLogin": "Remembered it? Back to login",
    "auth.needEmail": "Please enter your email first",
    "auth.codeSent": "Verification code sent",
    "auth.sendCodeFailed": "Failed to send code",
    "auth.registerSuccess": "Registered successfully",
    "auth.registerFailed": "Registration failed",
    "auth.resetSuccess": "Password reset successfully",
    "auth.resetFailed": "Password reset failed",
    "auth.loginFailed": "Login failed, please check your account and password",
    "auth.retryLater": "Please try again in {minutes} minutes",
    "profile.title": "Profile",
    "profile.subtitle": "View the current signed-in account.",
    "profile.accountInfo": "Account Info",
    "profile.username": "Username",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.role": "Role",
    "profile.userId": "User ID",
    "profile.status": "Status",
    "profile.statusActive": "Active",
    "profile.statusDisabled": "Disabled",
    "profile.createdAt": "Created At",
    "profile.updatedAt": "Updated At",
    "profile.roleAdmin": "Admin",
    "profile.roleBuyer": "User",
    "profile.navProfile": "Profile",
    "profile.navOrders": "My Orders",
    "profile.navSecurity": "Account Security",
    "profile.quickActions": "Quick Actions",
    "profile.viewOrders": "View Orders",
    "profile.goAdmin": "Open Admin",
    "profile.accountSecurity": "Account Security",
    "profile.accountSecurityDesc": "Manage login password, email verification, and account status.",
  },
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "zh-CN"
  const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY)
  return storedLanguage === "zh-TW" || storedLanguage === "en" ? storedLanguage : "zh-CN"
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage)

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage)
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage)
  }, [])

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key, fallback) => translations[language][key] ?? translations["zh-CN"][key] ?? fallback ?? key,
    st: (text) => language === "zh-CN" ? text : staticTranslations[language]?.[text] ?? text,
  }), [language, setLanguage])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within LanguageProvider")
  return context
}
